### ISSUE TITLE
fastqc configuration problem

### ISSUE THREAD

**Issue by MK108-Potato-Launcher** [jwschroeder3/wanglab_ngs_analysis#3]
I encountered issue as denoted in https://www.biostars.org/p/372867/ (No config files found, fail to analyze .fastq file)
This is due to the deficient of installing fastqc from ubuntu repo. The workaround I used is: 
Copy the txt files in fastqc repo (https://github.com/s-andrews/FastQC/tree/master/Configuration) into /etc/fastqc/Configuration folder (assuming that you have root/sudo privileges). If system doesn't have such directory, create the directory and copy the files. 

After doing this, fastqc works well.

**Comment by jwschroeder3** [comment]
I've updated the README.md to reflect the fix if a user receives this error.
